In [10]:
import pandas as pd
from dotenv import load_dotenv
import os

In [11]:
df = pd.read_csv("RAG/mental_health_counseling_conversations_combined_dataset.csv")

In [12]:
df.head()

,Context,Response
0,I'm going through some things with my feelings...,"If everyone thinks you're worthless, then mayb..."
1,I'm going through some things with my feelings...,"Hello, and thank you for your question and see..."
2,I'm going through some things with my feelings...,First thing I'd suggest is getting the sleep y...
3,I'm going through some things with my feelings...,Therapy is essential for those that are feelin...
4,I'm going through some things with my feelings...,I first want to let you know that you are not ...

In [13]:
df[df['Response'] == '']

Empty DataFrame
Columns: [Context, Response]
Index: []

In [14]:
df[df["Response"].isna()]

                                                Context Response
2434  From the moment I wake up, I hear what I think...      NaN
3006  I’m trying to make marriage work after a split...      NaN
3223  Every winter I find myself getting sad because...      NaN
3224  Does counseling really do anything that can he...      NaN

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(3507, 2)

Empty DataFrame
Columns: [Context, Response]
Index: []

In [18]:
grouped = (
    df.groupby("Context")["Response"]
      .apply(list)
      .reset_index()
)

for res in  grouped.iloc[11]['Response']:
    print(res)

since you realize your sense of trust was broken, withdrawing from close relationships, makes sense.This may be your Self giving you natural time to recuperate from emotional pain.Also it is your chance to think over how to handle yourself differently in future relationships.Maybe this process requires more time than you'd like.Having patience is very difficult when a person feels hurt.A therapist of your own may be a good idea so you have someone for guidance and to chart your progress w you.This may feel less lonely and help you tolerate the waiting period till you're better
Sounds like you need closure. I'm sure your doing your best to overcome this feeling but seem to be struggling with your own happiness. Trust God no one else. Give this some time and don't close yourself off to the world or the people who love you. Be open hearted and minded. And know that no matter what reason your ex walked out of your life, she missed out on how great of a person you truly are and may have had personal issues of her own.
Sounds like you need closure. I'm sure your doing your best to overcome this feeling but seem to be struggling with your own happiness. Trust God no one else. Give this some time and don't close yourself off to the world or the people who love you. Be open hearted and minded. And know that no matter what reason your ex walked out of your life, she missed out on how great of a person you truly are and may have had personal issues of her own.
since you realize your sense of trust was broken, withdrawing from close relationships, makes sense.This may be your Self giving you natural time to recuperate from emotional pain.Also it is your chance to think over how to handle yourself differently in future relationships.Maybe this process requires more time than you'd like.Having patience is very difficult when a person feels hurt.A therapist of your own may be a good idea so you have someone for guidance and to chart your progress w you.This may feel less lonely and help you tolerate the waiting period till you're better

In [32]:
grouped.shape

(994, 2)

In [103]:
duplicates_counter = 0


def count_duplicates(responses: list[str]):
    global duplicates_counter
    passed = set()
    for i in range(len(responses)):
        if i in passed:
            continue
        for j in range(i+1, len(responses)):
            if j in passed:
                continue
            if responses[i] == responses[j]:
                duplicates_counter+=1
                passed.add(j)

In [104]:
grouped['Response'].apply(count_duplicates)

0      None
1      None
2      None
3      None
4      None
       ...
989    None
990    None
991    None
992    None
993    None
Name: Response, Length: 994, dtype: object

In [ ]:
print("Number of duplicates: ", duplicates_counter)

768

In [106]:
def remove_duplicates(responses: list[str]):
    passed = set()
    for i in range(len(responses)):
        if i in passed:
            continue
        for j in range(i+1, len(responses)):
            if j in passed:
                continue
            if responses[i] == responses[j]:
                passed.add(j)

    for i in sorted(list(passed), reverse=True):
        responses.pop(i)

In [107]:
grouped['Response'].apply(remove_duplicates)

0      None
1      None
2      None
3      None
4      None
       ...
989    None
990    None
991    None
992    None
993    None
Name: Response, Length: 994, dtype: object

In [108]:
duplicates_counter = 0
grouped['Response'].apply(count_duplicates)

0      None
1      None
2      None
3      None
4      None
       ...
989    None
990    None
991    None
992    None
993    None
Name: Response, Length: 994, dtype: object

In [ ]:
print("Number of duplicates: ", duplicates_counter)

0

In [ ]:
DS_NAME = os.getenv('GROUPED_RAG_DATASET')
grouped.to_csv(f"{DS_NAME}.csv")